### ISSUE TITLE
Publish to unpkg CDN

### ISSUE THREAD

**Issue by cesarqdt** [emilhe/dash-extensions#284]
Hi! Thanks for this project that brings new components to the Dash ecosystem!

I would like to use dash-extensions for a Dash project in production where I prefer to use the unpkg CDN for delivering the JS sources of Dash components. However I noticed that the sources for dash-extensions are inexistent on unpkg.

https://unpkg.com/dash_extensions
```
Cannot find package dash_extensions@latest
```

Do you plan to publish your components to NPM to make them available on unpkg?
Thanks

**Comment by emilhe** [comment]
Thanks! I never though about it no, but I guess it would make sense. I have just published the latests non-rc release (`1.0.3`) to npm. Could you test if it works as intended? If so, I'll add the step to the CICD pipeline, thus making all new releases available.

**Comment by cesarqdt** [comment]
Thanks @emilhe, I have tested on 1.0.3 and confirm that the packages are in the CDN and the pages are rendering from it. Please add it into the CICD pipeline so new releases would also upload the unpkg.

**Comment by emilhe** [comment]
I have added the required steps to the pipeline from version 1.0.4 :)

**Comment by cesarqdt** [comment]
Hi @emilhe since last week this stoped working, any idea why the JS are not being loaded?
Here's the screenshot of the network tab (which was 200 response code last week).
<img width="1236" alt="Screenshot 2023-10-10 at 11 18 22" src="https://github.com/emilhe/dash-extensions/assets/97994493/fe5a2a6f-348d-4ef0-b50e-b01e130821fa">
