### ISSUE TITLE
Support for Flask Caching 2.1.0

### ISSUE THREAD

**Issue by mvheimburg** [emilhe/dash-extensions#296]
Missing support for Flask Caching 2.1.0 and by extension Flask 3.0.0.

**Comment by yzcheung** [comment]
I use poetry for dependency management, but I encountered a dependency problem and could not install dash-extensions. It would be very grateful if this project could upgrade flask-caching to 2.1.0 and dash to the latest version 2.14.2.

**Comment by emilhe** [comment]
Should be fixed in the 1.0.10 realease. Please re-open, if you still have any issues.
