### ISSUE TITLE
Serverside how to use memory as backend

### ISSUE THREAD

**Issue by Liripo** [emilhe/dash-extensions#303]
Hello: 
I haven't found any examples of using memory as the Serverside backend instead of using disk cache. Are there any examples?
Thanks.

**Comment by emilhe** [comment]
A class is not included for in-memory storage (as you would typically run out of memory too quickly), but you could make one with a few lines of code if you want - just follow the instructions from the docs,

https://www.dash-extensions.com/transforms/serverside_output_transform#a-backends

**Comment by Liripo** [comment]
Thanks.
