### ISSUE TITLE
Bump `more-itertools` dependency

### ISSUE THREAD

**Issue by samclz** [emilhe/dash-extensions#329]
Hello!
I'm trying to deploy an app using `dash-extensions` as well as another package, both depending on `more-itertools`. However, `dash-extensions` depends on version `^9.0.0` and the other package on `>=10.2.0, <11.0.0`.
Is there any reason why `dash-extensions` is incompatible with `more-itertools>=10.2.0`, or could it be bumped?
The `more-itertools` [documentation](https://more-itertools.readthedocs.io/en/stable/versions.html) suggests very few breaking changes between versions 9 & 10.
Cheers :)

**Comment by emilhe** [comment]
Should be fixed in the 1.0.16 release
